version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: receipt-postgres
    environment:
      POSTGRES_DB: receipt_db
      POSTGRES_USER: shikhar
      POSTGRES_PASSWORD: shikhar
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./migrate_to_multi_user.sql:/docker-entrypoint-initdb.d/02-migration.sql
      - ./user_management.sql:/docker-entrypoint-initdb.d/03-user-management.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shikhar -d receipt_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: receipt-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  streamlit-app:
    build: .
    container_name: receipt-streamlit
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://shikhar:shikhar@postgres:5432/receipt_db
      - OLLAMA_BASE_URL=http://ollama:11434
      - APP_USERNAME=alice
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
